### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Glomzubuk** [SebastienFRA/LVASI#5]
Hello!
In the readme, you mention the project being open-source:
> The project is of course in "open-source", you are free to modify it, complete it, improve it, etc.

What about distribution and attribution? Can the software be used commercially? Who is liable in case of software errors?
I recommend picking an already existing license, according to you preferences on this subject.

If you don't know to start about this, here's a website that can help with your decision: https://choosealicense.com/

**Comment by SebastienFRA** [comment]
Hello !

Thank you for your message ;)
Indeed, being a beginner in the field of programming, I did not inquire about the attribution of the license. I foolishly thought that pointing out that the project is open-source was enough.
Thanks to you, I took a closer look and added the license directly to the repo.

The license is now available ;)
